planetarium/agent8

app/lib/common/prompts/optimized.ts
This PR fixes optimized prompts to follow changes in https://github.com/planetarium/agent8/commit/005e828b1340bf1b5b8fe153ee3ead883bc4d7c4
=> Fix optimized prompts

app/lib/modules/llm/providers/anthropic.ts, app/lib/modules/llm/providers/open-router.ts
=> feat: extend maxTokenAllowed for sonnet 3.7

app/routes/api.chat.ts
=> feat: remove verbose log

app/components/chat/Chat.client.tsx, app/components/chat/Messages.client.tsx, app/components/workbench/Workbench.client.tsx, app/lib/modules/llm/manager.ts, app/lib/modules/llm/whitelist.ts, app/lib/persistenceGitbase/api.client.ts, app/lib/stores/workbench.ts, app/routes/api.models.ts, app/utils/fileUtils.ts, app/utils/selectStarterTemplate.ts
- If the code modified by the user is the same as the following, it is automatically committed. (Upon the next prompt, deploy)
- If the preview is already open, do not run "npm run dev" again. (However, if server.js has changed, rerun it.)
=> feat: commit user manual edits.

app/components/chat/Chat.client.tsx, app/lib/persistenceGitbase/api.client.ts, app/lib/persistenceGitbase/gitlabService.ts, app/lib/persistenceGitbase/useGitbaseChatHistory.ts, app/lib/verse8/middleware.ts, app/routes/api.me.ts, app/utils/markdown.ts, app/utils/url.ts
- Send information to the superior service, verse8, when the URL is changed.
- useGitbaseChatHistory works on changing history.
=> feat: change the URL sync logics

app/components/@settings/tabs/features/FeaturesTab.tsx, app/components/chat/Messages.client.tsx, app/lib/hooks/useSettings.ts, app/lib/persistenceGitbase/api.client.ts, app/lib/persistenceGitbase/gitlabService.ts, app/lib/stores/settings.ts, app/routes/api.select-template.ts
created to prevent the use of the GitLab repository as a persistent system, serving as a feature for developers.
=> feat: add temporary mode feature and integrate with settings

.gitignore, app/components/@settings/tabs/features/FeaturesTab.tsx, app/components/chat/Chat.client.tsx, app/components/workbench/Workbench.client.tsx, app/lib/hooks/useSettings.ts, app/lib/persistenceGitbase/api.client.ts, app/lib/stores/files.ts, app/lib/stores/settings.ts, app/lib/stores/workbench.ts, app/routes/api.gitlab.commits.ts, app/utils/constants.ts
- auto generate .env and change deployment method
- add setting to enable agent8 deploy
=> feat: apply auth in the publishing process. 

app/lib/.server/llm/search-resources.ts, app/lib/.server/llm/search-vectordb.ts, app/routes/api.chat.ts, app/utils/selectStarterTemplate.ts, worker-configuration.d.ts
=> feat: separate the production environment

app/lib/.server/llm/stream-text.ts, app/lib/.server/llm/tools/file-search.ts, app/lib/common/prompts/agent8-prompts.ts, app/routes/api.chat.ts, app/routes/api.enhancer.ts, app/routes/api.llmcall.ts, app/utils/fileUtils.ts
- Pre-organization before the main work
- Add file tool (#68)
=> feat: simplify chat logic & add file search tool

app/components/chat/Markdown.tsx, app/components/chat/ToolCall.tsx, app/components/chat/ToolResult.tsx, app/lib/modules/mcp/toolset.ts
This PR fixes two problems.
1. it parallelizes MCP toolset up for multiple servers
2. it fixes rendering errors on `<ToolCall>` and `<ToolResult>`, when they arrive first before any text response.
=> Fix MCP/Tool calling related features

app/lib/.server/llm/stream-text.ts, app/lib/.server/llm/utils.ts, app/lib/modules/llm/providers/anthropic.ts, app/lib/modules/llm/providers/open-router.ts, app/lib/verse8/credit.ts, app/lib/verse8/middleware.ts, app/routes/api.chat.ts, app/routes/api.enhancer.ts, app/routes/api.image-description.ts, app/routes/api.startcall.ts, app/utils/constants.ts
- apply Anthropic cache
- fix image upload not working.
- fix prompt enhancer not working
=> feat: renovate chat chores

app/components/chat/Markdown.tsx, app/components/workbench/Preview.tsx, app/lib/.server/llm/stream-text.ts, app/lib/.server/llm/tools/vectordb.ts, app/lib/common/prompts/agent8-prompts.ts, app/lib/modules/llm/whitelist.ts, app/routes/api.chat.ts
The tool result is very large, and it is expensive to keep the context maintained. 
After this, the parsing error is also solved.
=> wrap toolCall, toolResult tag

app/components/chat/BaseChat.tsx, app/components/chat/Chat.client.tsx, app/components/chat/Messages.client.tsx, app/components/ui/Slider.tsx, app/components/workbench/DiffView.tsx, app/components/workbench/Workbench.client.tsx, app/lib/persistenceGitbase/api.client.ts, app/lib/persistenceGitbase/gitlabService.ts, app/lib/stores/workbench.ts, app/routes/api.gitlab.diff.ts
- Implemented the ability to view the commit changelog (diff) in the message interface
- Added GitLab commit diff API endpoint
1. In the dialog, find the message containing the previously performed commit
2. Click the "View diff for this message" button on that message
3. The top slider tab enables the Diff option and automatically switches to the Diff view
4. View the change history for that commit in Diff view
- Added code is marked with a green background
- Deleted code is marked with a red background
- Browse change history by file
=> feat: add the ability to view commit diffs in Messages

app/components/header/Header.tsx, app/components/sidebar/Menu.client.tsx
https://github.com/planetarium/verse8-vibe/issues/4#issue-3024741347
- Added top margin to header and sidebar when chat is not started
- Fixed height calculation for sidebar
=> fix: adjust header and sidebar margins based on chat state

app/lib/stores/settings.ts
- add Feat/default mcp servers
=> add Feat/default mcp servers

app/components/@settings/tabs/features/FeaturesTab.tsx, app/lib/hooks/useSettings.ts, app/lib/stores/settings.ts
=> add reset MCP Servers

app/lib/container/interfaces.ts, app/lib/container/remote-container-impl.spec.ts, app/lib/container/remote-container-impl.ts, app/lib/container/webcontainer-impl.ts, app/lib/shared/agent8-container-protocol/.editorconfig, app/lib/shared/agent8-container-protocol/README.md, app/lib/shared/agent8-container-protocol/src/remote-container-protocol.ts, app/lib/stores/files.ts, app/utils/shell.ts
test should be fixed & stdout race condition should be addressed
=> feat: remote-container process spawning & IO

app/components/@settings/tabs/features/FeaturesTab.tsx, app/components/chat/BaseChat.tsx, app/components/chat/McpSseServerManager.tsx, app/lib/stores/settings.ts
https://github.com/orgs/planetarium/projects/127/views/1?pane=issue&itemId=108542995&issue=planetarium%7Cagent8%7C104
- Added the ability to select MCP TOOL (SSE SERVER) above the prompt.
- Modified the functionality so that only user-added MCP TOOLs can be deleted.
=> feat: add the MCP TOOL (SSE SERVER) selection above the prompt

app/lib/container/remote-container-impl.spec.ts, app/lib/container/remote-container-impl.ts, app/lib/container/webcontainer-impl.ts
Also, it makes `webcontainer-impl.ts` to use `RemoteContainer` for testing.
=> fix: shell related features for RemoteContainer

app/lib/container/remote-container-impl.spec.ts, app/lib/container/remote-container-impl.ts
=> feat: preview features for RemoteContainer

app/lib/container/remote-container-impl.ts, app/lib/shared/agent8-container-protocol/src/remote-container-protocol.ts
rel: https://github.com/planetarium/agent8-container-agent/pull/19
=> feat: websocket heartbeat

app/lib/container/remote-container-impl.ts
As title said, this PR fixes `executeCommand()` of `ShellSession` from `RemoteContainer`, to make it processes consequent commands properly.
=> fix: executeCommand overwrapping

app/lib/container/remote-container-impl.ts
Like #129, this PR fixes `waitTillOscCode()` from `RemoteContainer`, to handle multiple OSC code in one chunk properly.
It would fix command stuck for consequent commands.
=> Fix waitTillOscCode

app/components/chat/Chat.client.tsx, app/lib/persistenceGitbase/api.client.ts, app/lib/persistenceGitbase/utils.ts, app/lib/stores/workbench.ts
fix belows:
- Commit to the wrong branch when there are user changes.
- Prevent action execution for already committed messages.
=> fix: task branch issues

app/components/header/Header.tsx, app/components/sidebar/Menu.client.tsx, app/lib/stores/menu.ts
https://github.com/orgs/planetarium/projects/127/views/1?pane=issue&itemId=110157462&issue=planetarium%7Cagent8%7C140
---
- Change to open and close the sidebar with a click instead of a mouse hover
- Added tooltips to toggle icons
=> fix: improve sidebar menu UX and toggle behavior

app/lib/container/index.ts, app/routes/_index.tsx
This PR defers container initialization, to accept v8 access token provided by `INIT` window message properly.
=> fix: container initialization properly with v8 access token

app/components/chat/McpServerManager.tsx, app/lib/stores/settings.ts
=> add ui-mcp

app/lib/container/remote-container-impl.ts
This PR adds retrying logic for remote container requests
=> fix: retry container request

app/lib/modules/mcp/toolset.ts
Continued from #151 
This PR limits parallelism of `createToolSet()`, to care about CloudFront Worker's concurrency limitation.
=> fix: limit parallelism of createToolSet()

app/components/chat/McpServerManager.tsx, app/lib/stores/settings.ts
=> only enable All-in-One

app/components/chat/Chat.client.tsx, app/lib/hooks/useMessageParser.ts, app/lib/persistenceGitbase/api.client.ts, app/lib/runtime/action-runner.ts, app/lib/stores/workbench.ts
=> fix: omitted changes due to timing problems.

app/components/chat/BaseChat.tsx, app/components/chat/FilePreview.tsx, app/components/workbench/ResourcePanel.tsx, app/utils/constants.ts
- allow `.vrm` in the attachment extension list
- accept VRM in chat file uploads and treat it as a 3D model
- detect VRM files when rendering file previews
- handle VRM assets in the workbench resource panel
fixes #86
=> feat: support VRM upload and preview

app/root.tsx, app/utils/captureService.ts, app/utils/postMessageUtils.ts, package.json, pnpm-lock.yaml
https://github.com/orgs/planetarium/projects/127/views/1?pane=issue&itemId=110584379&issue=planetarium%7Cagent8%7C150
- Added the ability to capture web pages using html2canvas.
=> feat: add screenshot capture

app/components/@settings/core/AvatarDropdown.tsx, app/components/@settings/core/ControlPanel.tsx, app/components/@settings/shared/components/DraggableTabList.tsx, app/components/@settings/shared/components/TabManagement.tsx, app/components/@settings/shared/components/TabTile.tsx, app/components/@settings/tabs/connections/ConnectionsTab.tsx, app/components/@settings/tabs/connections/GithubConnection.tsx, app/components/@settings/tabs/connections/components/ConnectionForm.tsx, app/components/@settings/tabs/connections/components/CreateBranchDialog.tsx, app/components/@settings/tabs/connections/components/PushToGitHubDialog.tsx, app/components/@settings/tabs/connections/components/RepositorySelectionDialog.tsx, app/components/@settings/tabs/debug/DebugTab.tsx, app/components/@settings/tabs/event-logs/EventLogsTab.tsx, app/components/@settings/tabs/features/FeaturesTab.tsx, app/components/@settings/tabs/notifications/NotificationsTab.tsx, app/components/@settings/tabs/profile/ProfileTab.tsx, app/components/@settings/tabs/providers/cloud/CloudProvidersTab.tsx, app/components/@settings/tabs/providers/local/LocalProvidersTab.tsx, app/components/@settings/tabs/providers/local/OllamaModelInstaller.tsx, app/components/@settings/tabs/providers/service-status/ServiceStatusTab.tsx, app/components/@settings/tabs/providers/status/ServiceStatusTab.tsx, app/components/@settings/tabs/settings/SettingsTab.tsx, app/components/@settings/tabs/task-manager/TaskManagerTab.tsx, app/components/@settings/tabs/update/UpdateTab.tsx
- switch icon classes in settings to accent color
- `pnpm test` *(fails: Connect Timeout Error)*
=> fix: update Control Panel icons to cyan

app/components/chat/Chat.client.tsx
As title suggests, this PR fixes some codes relating `Container.mount()`, to catch exception from `.mount()` properly. 
Currently, it doesn't perform any recovery codes yet. but I'll add them after check that.
=> fix: container.mount related codes to catch properly

app/components/workbench/Workbench.client.tsx, app/lib/container/remote-container-impl.ts
- move shell check from workbench to remote-container
- basic function that using in shell command
- more effective
=> move shell check from workbench to remote-container

app/components/workbench/Preview.tsx, app/lib/persistenceGitbase/useGitbaseChatHistory.ts
related [issue](https://github.com/orgs/planetarium/projects/127?pane=issue&itemId=112027810)
=> Add device presets with accurate pixel dimensions

app/components/chat/BaseChat.tsx, app/styles/variables.scss
- Modified the width and padding of the pre-chat prompt.
- Modified ModelSelector tooltip position after chat starts.
=> refactor: modify the width of the pre-chat prompt

app/root.tsx
=> add hotjar to header

app/lib/.server/llm/stream-text.ts, app/lib/common/prompts/agent8-prompts.ts, pnpm-lock.yaml
Add getProjectDocsPrompt to automatically read and include all markdown files from docs/ folder in the system prompt for better context awareness.
=> feat: auto-include docs folder in system prompt Add getProjectDocsPrompt

app/utils/previewErrorFilters.ts
=> Fix linter error

app/components/chat/Chat.client.tsx, app/components/chat/ChatAlert.tsx, app/components/chat/TaskBranches.client.tsx, app/components/chat/TaskMessages.client.tsx, app/components/workbench/Preview.tsx, app/lib/persistenceGitbase/useGitbaseChatHistory.ts
- Fix issues where errors are being caught unnecessarily  
- Fix the missing error message.
=> refactor: error handling

app/components/chat/Chat.client.tsx, app/components/header/Header.tsx, app/components/header/HeaderVisibilityButton.client.tsx, app/components/ui/NotFoundPage.tsx, app/lib/persistenceGitbase/gitlabService.ts, app/lib/persistenceGitbase/useGitbaseChatHistory.ts, app/routes/api.gitlab.commits.ts, app/routes/api.gitlab.diff.ts, app/routes/api.gitlab.download.ts, app/routes/api.gitlab.task-branches.ts, app/routes/api.gitlab.visibility.ts
- **프로젝트 공개/비공개 설정**: Header에 Public/Private 토글 버튼 추가
- **권한 기반 접근 제어**: Private 프로젝트는 소유자만 접근 가능
- **404 에러 페이지**: 접근 권한이 없을 때 사용자 친화적인 404 페이지 표시
- **GitlabService 확장**: 프로젝트 visibility 관련 메서드 추가
- **API 엔드포인트 추가**:  추가
- **기존 API 보안 강화**: 모든 관련 API에 권한 체크 추가
- **컴포넌트 분리**: 재사용 가능한 NotFoundPage 컴포넌트 생성
- **권한 검증**: 프로젝트 소유자만 visibility 변경 가능
- **정보 노출 방지**: Private 프로젝트 존재 여부 숨김
- **일관된 접근 제어**: 모든 프로젝트 관련 API에 동일한 권한 체크 적용
=> Add project visibility control and access permission

app/lib/.server/llm/stream-text.ts, app/lib/common/prompts/agent8-prompts.ts, app/lib/persistenceGitbase/api.client.ts, app/lib/persistenceGitbase/gitlabService.ts, app/routes/api.gitlab.fork.ts, app/routes/spin.tsx
- Add SHA parameter support to spin route
- Allow specifying source branch/commit when creating spin projects  
- Update fork project to accept source SHA with default to develop
- Add source project metadata for better tracking
- **spin.tsx**: Added URL parameter  for branch/commit selection
- **Fork functionality**: Updated to accept source SHA instead of hardcoded 'develop'
- **Metadata tracking**: Added source project information for better context
- Spin functionality now supports specifying different source branches/commits
- Default behavior remains unchanged (still uses 'develop' if no SHA specified)
- Fork process includes source metadata for improved tracking
Closes #[issue-number] (if applicable)
=> feat: Add branch selection support for spin functionality

app/components/chat/BaseChat.tsx, app/components/chat/Chat.client.tsx, app/lib/.server/llm/stream-text.ts, app/lib/common/prompts/agent8-prompts.ts, app/lib/persistenceGitbase/api.client.ts, app/lib/persistenceGitbase/gitlabService.ts, app/routes/api.gitlab.fork.ts, app/routes/spin.tsx
이 PR은 사용자가 첫 번째 요청 시 템플릿 설정 과정에 대한 진행 상황을 표시하는 로딩 인디케이터를 추가합니다.
- 요청 분석 단계와 템플릿 선택 단계에 대한 진행 상황 표시
- 템플릿 설정 중 명확한 로딩 상태로 사용자 경험 개선
- 요청 분석 및 기본 프로젝트 설정에 대한 진행 메시지 표시
- 완료 또는 오류 발생 시 진행 상황 표시 정리
- 사용자가 템플릿 선택 및 설정 과정 동안 더 나은 피드백을 받을 수 있음
- 로딩 상태가 명확하게 표시되어 사용자가 프로세스가 진행 중임을 알 수 있음
- 각 단계가 완료되면 시각적 피드백을 제공하여 사용자 신뢰도 향상
=> feat: Add progress indicators for template setup process

app/components/workbench/Workbench.client.tsx, app/lib/container/remote-container.ts
Amend #253  due to reproducing #248, and (re) address #252 again.
- Revert badb6b1e5e489d68234970d40b27992813692af0
- Elide unnecessary propmt waiting after preview showing
=> Different approach for #252

app/components/chat/SendButton.client.tsx, app/components/chat/TaskBranches.client.tsx, app/components/chat/TaskMessages.client.tsx, app/components/header/HeaderDeployButton.client.tsx, app/components/workbench/Workbench.client.tsx
- Added `data-track` attributes to user action buttons for GTM/GA analytics.
=> feat: add analytics tracking to user action buttons

app/lib/modules/llm/whitelist.ts
모델 화이트리스트의 GPT-5에서 userSelectable 속성 제거
=> fix: remove userSelectable property from GPT-5 in model whitelist

app/lib/stores/workbench.ts, vite.config.ts
- fix: improve verseId reuse logic to resolve duplicate entry error during deployment
- fix: resolve Chrome DevTools 404 error and improve code quality
=> fix: improve verseId reuse logic to resolve duplicate entry error during deployment

app/components/editor/codemirror/CodeMirrorEditor.tsx
- Prevent EditorView crashes with safe dispatch mechanism
- Add automatic editor view recreation on error occurrence  
- Prevent EditorView-related runtime errors
- Final state synchronization to resolve editor-document content mismatch after AI code streaming completion
=> refactor: editorview error prevention

app/components/workbench/ResourcePanel.tsx, app/lib/verse8/api.ts
=> feat: add call Upload asset API

app/lib/.server/llm/constants.ts, app/lib/.server/llm/stream-text.ts, app/lib/.server/llm/tools/action.ts, app/lib/.server/llm/tools/file-search.ts, app/lib/common/prompts/agent8-prompts.ts, app/routes/api.chat.ts, app/routes/api.startcall.ts
=> feat: auto-read unread files on submit_artifact call

app/components/chat/BaseChat.tsx, app/components/chat/Chat.client.tsx, app/components/chat/McpServerManager.tsx, app/root.tsx
Mobile UX enhancements and performance optimizations for pre-chat screen.
- Responsive MCP Server Manager with React Portal rendering and enhanced click detection
- WebP background image preloading for faster mobile loading
- Improved color tab logic and state synchronization
- Conditional prompt persistence based on chat state
- Gradient title styling
- Better dropdown UX across all interactive elements
=> feat: enhance mobile UX and performance for pre-chat screen

app/components/chat/Chat.client.tsx, app/lib/modules/llm/providers/google.ts
=> fix: use gemini-1.5-flash-latest model problem
