planetarium/agent8

app/lib/.server/llm/utils.ts, app/lib/runtime/message-parser.spec.ts, app/lib/runtime/message-parser.ts, app/routes/api.chat.ts
This PR reverts #20 and fixes #19 by ~assigning `user` role to previous context properly~ forcibly performing the previous action when new tag is coming into the message parser.
=> fix: incomplete `<boltAction>` tag issue (again)

app/components/chat/AssistantMessage.tsx, app/components/chat/Messages.client.tsx
Note) this PR should be merged after #42.
This PR fixes invalid message rendering for multipart message while streaming.
=> fix: eliminate duplicated string in multipart message

app/components/chat/Messages.client.tsx, app/lib/.server/llm/create-summary.ts, app/lib/.server/llm/search-resources.ts, app/lib/.server/llm/search-vectordb.ts, app/lib/.server/llm/select-context.ts, app/lib/hooks/useMessageParser.ts, app/utils/message.ts
Continued from #44 
This PR moves `message.parts` consideration from `Message.client.tsx` to `useMessageParser.ts`, to parse `message.parts` too.
=> fix: `boltArtfiact` parsing

app/lib/hooks/useMessageParser.ts, app/utils/logger.ts
Continued from #37 #42 #51 
`StreamingMessageParser.parse()` can't handle multipart message properly because AI SDK changes `message.id` when added new parts. (see also https://github.com/vercel/ai/issues/5318)
As workaround, this PR bypasses the problem of the parser by finding and not adding duplicate strings, and prevents the same sentence from being repeated when using the tool.
Also, it adds times to log messages for handy debug.
=> fix: duplicate contents on the multipart messages (again)

app/components/chat/Chat.client.tsx, app/lib/hooks/useMessageParser.ts, app/lib/persistenceGitbase/gitlabService.ts
Resolve the issue of existing content being duplicated when changing the message ID or retry message
=> feat: reset prev parsed message

wrangler.toml
See also: https://github.com/cloudflare/workerd/issues/698, https://developers.cloudflare.com/workers/configuration/compatibility-flags/#enable-cache-no-store-http-standard-api
This PR bumps `wrangler.toml` and turns on `cache_option_enabled`, to fix `The 'cache' field on 'RequestInitializerDict' is not implemented.` error.
=> fix: update wrangler.toml to care CloudFlare's cache error

app/components/@settings/tabs/features/FeaturesTab.tsx, app/components/ui/Switch.tsx, app/lib/api/cookies.ts, app/lib/hooks/useSettings.ts, app/lib/modules/mcp/config.ts, app/lib/modules/mcp/toolset.ts, app/lib/stores/settings.ts, app/routes/api.chat.ts, app/routes/api.llmcall.ts, app/styles/diff-view.css
See also: https://github.com/planetarium/mcp-agent8/issues/7
This PR adds `v8AuthIntegrated` flag to `MCPServerConfig`, and set v8 access token to header if MCP server has that flag.
=> feat: enables V8 Auth on MCP client

app/routes/api.llmcall.ts
This PR removes MCP injection from llmcall, which be used to select templates.
=> feat: remove MCP injection from llmcall

app/components/chat/Markdown.tsx
Continued from #77 
This PR fixes tool calling parsing again since #77's solution wasn't enough when payloads for `ToolCall` or `ToolResult` contains another HTML tags like `<div>`.
As workaround, it adds `&nbsp;` as prefix, to every content for `<ReactMarkdown>`.
=> fix: workaround for markdown parsing

app/lib/container/interfaces.ts, app/lib/container/webcontainer-impl.ts, app/lib/stores/files.ts, app/utils/shell.ts
Continued from #71 
This PR extracts shell related interfaces from existing codes and abstract duplicated usages.
Also, it moves `watchPaths()` from `Container.internal` to `FileSystem` to fit its purpose.
=> feat: introduce shell related interfaces

app/lib/.server/llm/stream-text.ts, app/lib/.server/llm/tools/docs.ts, app/lib/.server/llm/tools/file-search.ts, app/lib/.server/llm/tools/vectordb.ts, app/lib/common/prompts/agent8-prompts.ts
Add internal tools using a database.
- To separate unnecessary prompts and documents from the default system prompt.
- This feature is necessary, but Agent8 MPC is optional now, so I decided to make it as an internal tool. In the future, if Agent8 MCP becomes a default feature in the service, and there will be an on/off button for each function in Agent8 MCP, I think it would be good to consider migrating it.
=> feat: add internal tools (docs, vectordb)

app/components/workbench/Workbench.client.tsx, app/lib/container/index.ts, app/lib/container/interfaces.ts, app/lib/container/remote-container-impl.spec.ts, app/lib/container/remote-container-impl.ts, app/lib/container/webcontainer-impl.ts
This PR organizes boot phase for `RemoteContainer` and adds splash screen while booting.
Also, it changes proxy mechanism to reflect `fly replay` based router, for preview feature.
=> fix: remote container boot

app/components/workbench/Preview.tsx
Related to https://github.com/planetarium/agent8-container-agent/pull/22
This PR adds an emulation for `preview-message`, not supported in remote container directly.
=> feat: emulate preview-error message

app/lib/container/remote-container-impl.ts
Continued from #130 
This PR adjust reader lock check, to prevent invalid reading. it also adds log messages about execution too.
=> fix: `waitTillOscCode()` (again)

app/lib/stores/previews.ts
We don't need to synchronize localStorage between tabs for the previews since agent8 doesn't use localStorage to store chat no more. it can help to prevent web browser freezing.
=> fix: disable localStorage syncing

app/components/chat/BaseChat.tsx, app/components/chat/McpServerManager.tsx, app/lib/api/cookies.ts, app/lib/hooks/useSettings.ts, app/lib/modules/mcp/toolset.ts, app/lib/stores/settings.ts, package.json, pnpm-lock.yaml
Related to: https://github.com/planetarium/mcp-agent8/pull/17
As title said, This PR introduces Streamable-HTTP transport for MCP client, to stabilize connectivity.  additional work may be required to ensure connection stability, we will try to work based on this Streamable-HTTP due to SSE transport deprecation.
Also, it changes terms "MCP SSE Server" to "MCP Server" in identifier and messages, to help further readers.
=> feat: introduce streamable HTTP for MCP client

app/components/workbench/terminal/Terminal.tsx
Continued from #145 
This PR ensures that it always reads a portion of the previous buffer so that no lines are missed.
=> fix: missing terminal output

app/lib/api/cookies.ts, app/lib/stores/settings.ts
Continue from #136 
Note) This PR should be merged AFTER setting MCP servers to support streamable-http.
It changes URLs for the default MCP server, to connect with Streamable HTTP instead of SSE.
Also it changes setting key value due to migration.
=> feat: diverse MCP settings by changing setting keys

app/lib/modules/mcp/toolset.ts, app/routes/api.chat.ts
This PR forces new clients per each tool call instead of keeping clients, since [CloudFlare worker can't have more than six outgoing connections concurrently](https://developers.cloudflare.com/workers/platform/limits/?utm_source=chatgpt.com#simultaneous-open-connections).
=> fix: adjust lifecycle of MCP client for CF worker

app/lib/container/remote-container-impl.ts, app/routes/_index.tsx
This PR contains three changes
1. `RemoteContainerFactory` now causes page reload when given v8 access token isn't valid.
2. `initializeContainer()` is called only after the 'INIT' message is called if `VITE_ACCESS_CONTROL_ENABLED` is set.
3. `RemoteContainer` will attempt to reconnect to the target container up to three times.
=> fix: stabilize remote container

app/components/chat/ChatAlert.tsx, app/components/workbench/Preview.tsx, app/utils/previewErrorFilters.ts
- ignore a known benign preview error
- centralize preview error ignores in a util
- `pnpm test` *(fails: Error when performing the request to https://registry.npmjs.org/...)*
=> fix: handle preview Ethereum error

app/components/chat/ToolCall.tsx
issue: https://github.com/planetarium/agent8/issues/206
---
- Prevented JSON overflow in ToolCall components.
=> fix: prevent JSON overflow in ToolCall component

app/lib/container/remote-container-impl.ts
As title suggests, this PR forces `sendHeartbeat()` to use `sendRequest<T>()` instead of vanilla `websocket.send()` from `RemoteContainerConnection`, to fit `ContainerRequest` format.
=> fix: invalid heartbeat request format

app/components/header/Header.tsx, app/components/sidebar/Menu.client.tsx
This PR adds the ability to completely disable the sidebar menu using an environment variable.
- Added  environment variable support
- When set to 'true', hides the sidebar menu toggle button in the Header component
- When set to 'true', prevents the sidebar menu from rendering in Menu.client.tsx
- Provides a cleaner interface option for users who don't need the sidebar navigation
Add the following to your  file:
- ✅ Verified menu button is hidden when environment variable is set to 'true'
- ✅ Verified sidebar menu doesn't render when environment variable is set to 'true'
- ✅ Verified normal functionality when environment variable is 'false' or not set
Closes #243
=> feat: Add option to disable sidebar menu (#243)

app/components/chat/Chat.client.tsx, app/components/workbench/Workbench.client.tsx, app/lib/stores/workbench.ts
Closes: #236 
This PR adds `cd <workdir>` to prevent `.env` file lookup failing on `@agent8/deploy`.
=> fix: ensure workdir before @agent8/deploy

app/lib/.server/llm/stream-text.ts, app/lib/.server/llm/tools/docs.ts, app/lib/common/prompts/agent8-prompts.ts, app/routes/_index.tsx, pnpm-lock.yaml
Changed the source for vibe-starter-3d package documentation and enhanced 3D game development guidelines.
Key changes:
- **vibe-starter-3d docs source change**: Modified to fetch markdown files from `/spec` directory instead of `/docs` directory
- **Variable rename**: Changed `vibeStarter3dDocs` → `vibeStarter3dSpec` to reflect the new source
- **Function rename**: Changed `getVibeStarter3dDocsPrompt` → `getVibeStarter3dSpecPrompt`
- **3D starter prompt enhancement**: Enhanced `get3DStarterPrompt` with detailed game-type-specific guidelines, providing concrete map decoration instructions for various 3D game genres including FPS, Flight, Top-down, and MOBA games
=> refactor: Change vibe-starter-3d docs source from docs to spec and improve 3D starter prompt

app/lib/.server/llm/tools/vectordb.ts
- Use z.coerce.string() to resolve type conversion errors
- Prevent "Expected string, received number" validation errors
- Improve robustness by automatically converting numeric IDs to strings
=> fix: Auto-convert numeric IDs from LLM to strings using coerce

app/lib/stores/workbench.ts
Closes #248 
As title suggest, this PR fixes command skipping on deploy. this bug is caused by using the wrong method in the #245
=> fix: skipping `pnpm run build` when deploy

app/lib/container/remote-container.ts
Closes #252 
As title suggests, this PR fixes the kick code for terminal, to wait prompt OSC properly.
=> fix: kick after ^C for OSC code properly

app/components/workbench/Workbench.client.tsx, app/lib/container/interfaces.ts, app/lib/container/remote-container.ts, app/utils/shell.ts
When clients reconnect, new terminal processes (e.g., pid: 11397) were being created instead of reusing existing ones (e.g., pid: 11396). This caused the existing BoltShell-connected terminal to become unresponsive, breaking the user experience during network reconnections.
- `executeCommand` was using the original `terminal` instance instead of the currently connected terminal
- Terminal input/output streams were not being reconnected to new terminal instances
- No mechanism existed to reattach terminal streams when sessions were reused
- Replaced hardcoded `terminal` references with `currentTerminal` in `executeCommand`
- Added `currentTerminal` tracking for dynamic terminal switching
- Added `attachTerminal()` method to `ShellSession` interface
- Implemented `attachTerminalInput()` for …
=> fix: terminal session reuse on client reconnection

app/components/chat/Chat.client.tsx
- Clear cached prompt cookies when going back to pre-chat
- Set default Top-Down prompt on chat state reset
- Prevent stale user input from persisting across chat sessions
=> fix: reset textarea to default prompt when returning to pre-chat state
